<?php
$title = 'Add new album';
$this->headTitle($title);
?>
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('home/add'));

$fieldset = $form->get('album');

$title = $fieldset->get('title');
$title->setAttribute('class', 'form-control');
$title->setAttribute('placeholder', 'Post title');

$artist = $fieldset->get('artist');
$artist->setAttribute('class', 'form-control');
$artist->setAttribute('placeholder', 'Post artist');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->prepare();

echo $this->form()->openTag($form);
?>

    <fieldset>
        <div class="form-group">
            <?= $this->formLabel($title) ?>
            <?= $this->formElement($title) ?>
            <?= $this->formElementErrors()->render($title, ['class' => 'help-block']) ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($artist) ?>
            <?= $this->formElement($artist) ?>
            <?= $this->formElementErrors()->render($artist, ['class' => 'help-block']) ?>
        </div>
    </fieldset>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($fieldset->get('id'));
echo $this->form()->closeTag();
