<?php

$title = 'Details';
$this->headTitle($title);
$album = $this->album;
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<table class="table table-dark">
    <tr>
        <th>Title</th>
        <th>Artist</th>
    </tr>
    <tr>
        <td>
            <a><?= $this->escapeHtml($album->getTitle()) ?></a>
        </td>
        <td><?= $this->escapeHtml($album->getArtist()) ?></td>
    </tr>
</table>






